### ISSUE TITLE
Triggering 'Get latest data

### ISSUE THREAD

**Issue by curacat** [Blake-Haydon/United-Energy-EnergyEasy-API#1]

**Comment by curacat** [comment]
Hi Blake,

Lovely API, works a treat!
However, my read from yesterday was a lot lower than I expected, so I logged into Energy Easy and clicked the "Get latest data" button. After that, the reads were accurate.

**Comment by Blake-Haydon** [comment]
In my testing the data was correct after you waited a full day. I think this is because your data may have only been for half a day.

**Comment by Blake-Haydon** [comment]
I'll see if I can add that feature to the api!

**Comment by Blake-Haydon** [comment]
A refresh_data() method was implemented that mimics clicking the "Get latest data" button. As long as you run that at the start of your script it should work!

**Comment by curacat** [comment]
Sorry for the slow response!
Thank you, really appreciate it!
